FROM python:3.11.1-alpine3.17

WORKDIR /app
ADD /client /app/client
ADD /models /app/models
ADD /scraper /app/scraper
ADD .env /app/.env
ADD config.py /app/config.py
ADD main.py /app/main.py
ADD requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt
RUN echo "http://dl-cdn.alpinelinux.org/alpine/v3.16/community" >> /etc/apk/repositories
RUN apk add firefox-esr ca-certificates curl --no-cache \
    && curl -L https://github.com/mozilla/geckodriver/releases/download/v0.32.0/geckodriver-v0.32.0-linux-aarch64.tar.gz | tar xz -C /usr/local/bin \
    && chmod +x /usr/local/bin/geckodriver \
    && apk del curl 

CMD ["python", "main.py"]