on: 
  push:
    branches:
      - main

jobs:
  build_x64:
    runs-on: ubuntu-latest
    name: Builds the x64 docker image
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build the Image
        run: docker build -t scraper_64 -f Dockerfile_x64 .
      - name: Push to ghcr
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}_x64  # it will be lowercased internally
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ./Dockerfile_x64

  build_aarch64:
    runs-on: ubuntu-latest
    env:
      DOCKER_TARGET_PLATFORM: linux/arm64/v8
    name: Builds the arrch64 docker image
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU dependency
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build the Image
        run: docker buildx build -t scraper_aarch64 --platform linux/arm64 -f Dockerfile_aarch64 .
      - name: Push to ghcr
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}_aarch64  # it will be lowercased internally
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ./Dockerfile_aarch64
          